### ISSUE TITLE
takeLogin那里数组成员名错了 提示API错误

### ISSUE THREAD

**Issue by villainousx** [PrintNow/ChaoxingSign#1]
改成type可行 不知道原来是怎么样的
可以考虑加一下server酱~

**Comment by PrintNow** [comment]
好的，我看看

会加入 server 酱 的

**Comment by PrintNow** [comment]
已经修复，我这测试没问题。
另外已经添加 Server酱，需要自己配置 `config.php` 文件，里面有注释
