### ISSUE TITLE
server,配置不成功，sckey正确填写。但是网页一直说scerver没有配置

### ISSUE THREAD

**Issue by paper-people215** [PrintNow/ChaoxingSign#2]
server,配置不成功，sckey正确填写。但是网页一直说scerver没有配置

**Comment by PrintNow** [comment]
已知问题，我逻辑出错了，等待修复

**Comment by paper-people215** [comment]
收到！大佬加油

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Chuwen <notifications@github.com>
发送时间: Friday, June 12, 2020 9:25:42 AM
收件人: PrintNow/ChaoxingSign <ChaoxingSign@noreply.github.com>
抄送: paper-people215 <paper-people@outlook.com>; Author <author@noreply.github.com>
主题: Re: [PrintNow/ChaoxingSign] server,配置不成功，sckey正确填写。但是网页一直说scerver没有配置 (#2)


已知问题，我逻辑出错了，等待修复

―

**Comment by PrintNow** [comment]
@paper-people215 已经修复

**Comment by paper-people215** [comment]
发自我的iPad

在 2020年6月13日，下午12:20，Chuwen <notifications@github.com> 写道：

﻿

@paper-people215<https://github.com/paper-people215> 已经修复

**Comment by paper-people215** [comment]
请问，是不是只有登陆网页在运行，签到功能才能正常运行，我尝试几次，似乎关闭网页不太行

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Chuwen <notifications@github.com>
发送时间: Saturday, June 13, 2020 4:20:22 AM
收件人: PrintNow/ChaoxingSign <ChaoxingSign@noreply.github.com>
抄送: paper-people215 <paper-people@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [PrintNow/ChaoxingSign] server,配置不成功，sckey正确填写。但是网页一直说scerver没有配置 (#2)


@paper-people215<https://github.com/paper-people215> 已经修复

―

**Comment by paper-people215** [comment]
似乎有个错误，一直显示只能在8点至23点签到，除非把第10行注释掉才可以正常使用，谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Chuwen <notifications@github.com>
发送时间: Saturday, June 13, 2020 4:20:22 AM
收件人: PrintNow/ChaoxingSign <ChaoxingSign@noreply.github.com>
抄送: paper-people215 <paper-people@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [PrintNow/ChaoxingSign] server,配置不成功，sckey正确填写。但是网页一直说scerver没有配置 (#2)


@paper-people215<https://github.com/paper-people215> 已经修复

―

**Comment by PrintNow** [comment]
@paper-people215 感谢提醒，我测试时忘记改回来了

**Comment by paper-people215** [comment]
收到！！

发自我的iPad

在 2020年6月14日，下午4:58，xin yu <Paper-people@outlook.com> 写道：

﻿
请问，是不是只有登陆网页在运行，签到功能才能正常运行，我尝试几次，似乎关闭网页不太行

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Chuwen <notifications@github.com>
发送时间: Saturday, June 13, 2020 4:20:22 AM
收件人: PrintNow/ChaoxingSign <ChaoxingSign@noreply.github.com>
抄送: paper-people215 <paper-people@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [PrintNow/ChaoxingSign] server,配置不成功，sckey正确填写。但是网页一直说scerver没有配置 (#2)


@paper-people215<https://github.com/paper-people215> 已经修复

**Comment by PrintNow** [comment]
@paper-people215 这个你是要做一个定时访问网址的，是被动触发（也就是当你访问网址才会进行签到），定时访问网址服务有 阿里云、腾讯云、百度云... 等，叫 云监控，可以去了解

**Comment by paper-people215** [comment]
收到！谢谢大佬的答疑！

发自我的iPad

在 2020年6月15日，上午8:37，Chuwen <notifications@github.com> 写道：

﻿

@paper-people215<https://github.com/paper-people215> 这个你是要做一个定时访问网址的，是被动触发（也就是当你访问网址才会进行签到），定时访问网址服务有 阿里云、腾讯云、百度云... 等，叫 云监控，可以去了解
