### ISSUE TITLE
检测不到签到任务

### ISSUE THREAD

**Issue by noahcn** [PrintNow/ChaoxingSign#22]
rt，测试发起个签到，这边一直是   [getTaskID]没有待签到的任务

**Comment by missuo** [comment]
已修复，已经 `pull requests`。如果急用请访问 [https://github.com/missuo/ChaoxingSign](https://github.com/missuo/ChaoxingSign)。或者 `git clone https://github.com/missuo/ChaoxingSign.git`

**Comment by noahcn** [comment]
好了，感谢大佬
