### ISSUE TITLE
签到失败，错误原因：非法请求未配置

### ISSUE THREAD

**Issue by NAILIANGCHI** [PrintNow/ChaoxingSign#27]
![image](https://user-images.githubusercontent.com/85297838/170818186-bee03728-c64c-4b9e-ba92-64016073a1fd.png)
今天看运行日志发现提示签到失败，错误原因：非法请求未配置。

**Comment by missuo** [comment]
Fixed on [#32](https://github.com/PrintNow/ChaoxingSign/pull/32)

**Comment by NAILIANGCHI** [comment]
> Fixed on [#32](https://github.com/PrintNow/ChaoxingSign/pull/32)

OK，问题已解决正常运行
