### ISSUE TITLE
提示非法请求

### ISSUE THREAD

**Issue by moxiaowk** [PrintNow/ChaoxingSign#30]

**Comment by moxiaowk** [comment]
https://github.com/cxOrz/chaoxing-sign-cli/commit/13814bc24f3936abd7abb1a26265d4cd1880deea
可能是接口或参数变化了，大佬可以参考这个，这个手动签到项目可以用

**Comment by noahcn** [comment]
提示非法请求，等大佬修复

**Comment by BA7JCM** [comment]
我这也提示非法请求

**Comment by missuo** [comment]
一会我看看

**Comment by missuo** [comment]
Fixed on [#32](https://github.com/PrintNow/ChaoxingSign/pull/32)
